--- FIRST WE CREATE A DATABASE
CREATE DATABASE DEFORESTATION
  USE DEFORESTATION

--- NEXT WE IMPORTED OUR DATASETS AND PREVIEW IT TO CHECK FOR NULL VALUES

SELECT * FROM Forest_Area
SELECT * FROM Land_Area
SELECT * FROM Region

--- TO FILL UP NULL VALUES
SELECT forest_area_sqkm FROM Forest_Area WHERE forest_area_sqkm IS NULL;

SELECT total_area_sq_mi FROM Land_Area WHERE total_area_sq_mi IS NULL;

--- SINCE WE HAVE NULL VALUES, LETS GET THE AVERAGE 
SELECT AVG(forest_area_sqkm) FROM Forest_Area

SELECT AVG(total_area_sq_mi) FROM Land_Area

--- LETS FILL THE MISSING VALUES WITH AVG
UPDATE Forest_Area SET forest_area_sqkm = 391051.83952495
WHERE forest_area_sqkm IS NULL;

UPDATE Land_Area SET total_area_sq_mi = 457095.353337975
WHERE total_area_sq_mi IS NULL;

--- WE HAVE WORLD SHOWING AS COUNTRY NAME, THATS AN OUTLIER. TO REMOVE IT
DELETE FROM REGION 
WHERE REGION = 'WORLD'

--- NOW WE HAVE A CLEAN DATASET, LETS ANSWER THE QUESTIONS.
--- 1. WHAT ARE THE TOTAL NUMBER OF COUNTRIES INVOLVED IN DEFORESTATION

SELECT COUNT (DISTINCT COUNTRY_NAME )  AS COUNTRIES_INVOLVED_IN_DEFORSTATION FROM
(SELECT COUNTRY_NAME, FOREST_AREA_SQKM, YEAR, RANK() OVER(PARTITION BY COUNTRY_NAME ORDER BY FOREST_AREA_SQKM) RANK FROM Forest_Area) AS COUNTRIES_INVOLVED_IN_DEFORSTATION 
WHERE RANK !=1;
--- WE HAVE 176 COUNTRIES INVOLVED

--- 2. SHOW THE INCOME GROUP OF COUNTRIES HAVING TOTAL AREA RANGING FROM 75000 TO 150,000 SQUARE METER
---FIRST WE JOIN THE TWO TABLES INVOLVED USING JOIN, THEN WE SORT OUT THE AREAS RANGING FROM 75000 TO 150000

SELECT * FROM LAND_AREA L
JOIN REGION R ON L.COUNTRY_NAME = R.COUNTRY_NAME

SELECT DISTINCT L.COUNTRY_NAME, R.INCOME_GROUP FROM REGION R
JOIN LAND_AREA L ON R.COUNTRY_NAME = L.COUNTRY_NAME
WHERE TOTAL_AREA_SQ_MI BETWEEN 75000 AND 150000
ORDER BY INCOME_GROUP;
--- THE ABOVE SHOWS THAT WE HAVE 25 COUNTRIES WITH THIS RANGE 

---3. Calculate average area in square miles for countries in the 'upper middle income region'. Compare the result with the rest of the income categories

SELECT INCOME_GROUP, AVG(TOTAL_AREA_SQ_MI) AS AVERAGE_AREA FROM REGION R
JOIN LAND_AREA L ON R.COUNTRY_NAME = L.COUNTRY_NAME
GROUP BY INCOME_GROUP
HAVING INCOME_GROUP IN ('UPPER MIDDLE INCOME','HIGH INCOME', 'LOW INCOME', 'LOWER MIDDLE INCOME')
ORDER BY AVG(TOTAL_AREA_SQ_MI)DESC;
---ABOVE WE CAN SEE THAT WE HAVE MORE COUNTRIES IN THE UPPER MIDDLE INCOME CLASS

---4. Determine the total forest area in square km for countries in the 'high income' group. Compare result with the rest of the income categories.

SELECT INCOME_GROUP, SUM(FOREST_AREA_SQKM) AS TOTAL_FOREST_AREA FROM REGION R
JOIN FOREST_AREA F ON R.COUNTRY_NAME = F.COUNTRY_NAME
GROUP BY INCOME_GROUP
HAVING INCOME_GROUP IN ('UPPER MIDDLE INCOME','HIGH INCOME', 'LOW INCOME', 'LOWER MIDDLE INCOME')
ORDER BY SUM(FOREST_AREA_SQKM)DESC;

----5.Show countries from each region(continent) having the highest total forest areas

WITH HIGHEST_CTE AS 
(SELECT DISTINCT R.COUNTRY_NAME, REGION, F.FOREST_AREA_SQKM, DENSE_RANK() OVER(PARTITION BY REGION ORDER BY FOREST_AREA_SQKM DESC)AS RANK FROM REGION R
JOIN FOREST_AREA F ON R.COUNTRY_NAME = F.COUNTRY_NAME)
SELECT * FROM HIGHEST_CTE
WHERE RANK = 1;



















-




